import json

features_en = {
    "Suno AI": ["Generate full songs from text", "Multiple genre support (pop, rock, jazz, etc.)", "Lyrics, vocals, and instrumentation", "Fast generation in seconds", "Free tier available"],
    "Udio": ["Exceptional audio fidelity", "Realistic instrumental music", "Complex genre combinations", "Generous free tier", "High-quality vocal synthesis"],
    "AIVA": ["Orchestral/cinematic compositions", "Trained on classical scores", "Custom soundtrack creation", "Royalty-free licensing", "Multi-track arrangement"],
    "Mubert": ["Real-time music generation", "Endless adaptive streams", "Royalty-free for creators", "Mood and tempo control", "Electronic genre focus"],
    "Soundraw": ["Human-in-the-loop editing", "Regenerate specific sections", "Genre & mood selection", "Royalty-free licensing", "Fine-grained control"],
    "Boomy": ["Instant song creation", "Global music distribution", "Multiple genre templates", "Beginner-friendly UI", "No music theory needed"],
    "Riffusion": ["Spectrogram-based generation", "Visual sound editing", "Experimental AI approach", "Open-source foundation", "Unique sound manipulation"],
    "Beatoven.ai": ["Mood-based soundtrack generation", "Adapts to video narrative", "Royalty-free background music", "Timeline-based editing", "Designed for video creators"],
    "LANDR": ["AI-powered mastering", "Music distribution service", "Sample library access", "Plugin marketplace", "Collaboration tools"],
    "ElevenLabs Music": ["Deep learning music generation", "Natural-sounding compositions", "Genre versatility", "High-quality audio output", "From leading voice AI company"],
    "Jasper AI": ["50+ content templates", "Brand voice customization", "SEO-optimized writing mode", "Team collaboration features", "GPT-4 powered"],
    "Writesonic": ["AI article writer", "Chatsonic chatbot integration", "Paraphrasing tool", "Text-to-speech capabilities", "Affordable pricing tiers"],
    "Copy.ai": ["GTM workflow automation", "45% recurring commissions", "Sales outreach tools", "Content generation at scale", "Integrations with CRM"],
    "Rytr": ["40+ use cases supported", "30+ languages available", "Built-in plagiarism checker", "SEO analyzer included", "Budget-friendly pricing"],
    "Sudowrite": ["Story Engine for novels", "Beat Sheet plotting tool", "Expand/rewrite prose", "Character development tools", "Idea brainstorming"],
    "Claude": ["200K token context window", "Nuanced conversational AI", "Strong reasoning capabilities", "Code analysis & generation", "Safety-focused design"],
    "ChatGPT": ["Text, image & voice input", "Plugin ecosystem", "GPT-4o model access", "Code interpreter", "Massive user community"],
    "ProWritingAid": ["20+ writing reports", "Style & structure analysis", "Readability scoring", "Manuscript-level editing", "Integration with Word/Google Docs"],
    "Anyword": ["Predictive copy scoring", "Ad platform integration", "Data-driven optimization", "Performance analytics", "Conversion-focused AI"],
    "Midjourney": ["Stunning artistic quality", "Discord-based interface", "Style consistency", "High-resolution output", "Active creative community"],
    "DALL-E 3 / GPT Image": ["Seamless ChatGPT integration", "Complex prompt understanding", "High-quality image generation", "Text rendering capability", "Edit with inpainting"],
    "Adobe Firefly": ["Deep Creative Cloud integration", "Generative fill & expand", "Text-to-image generation", "Commercial safety", "Professional design tools"],
    "Stable Diffusion": ["Open-source & local", "Custom model training", "No content filters", "Community extensions", "Full creative control"],
    "Leonardo AI": ["Real-time generation", "Custom model training", "Game asset focus", "Consistent style output", "Pre-built style library"],
    "Canva AI": ["Magic Design automation", "Magic Write copy generation", "AI photo editing tools", "Drag-and-drop simplicity", "Social media templates"],
    "Ideogram": ["Best-in-class text rendering", "Logo and poster creation", "Photorealistic output", "Style control features", "Consistent brand assets"],
    "Recraft": ["Brand-trained AI models", "Consistent style across assets", "Vector and raster output", "Marketing team focused", "Color palette control"],
    "Clipdrop": ["Background removal tool", "AI upscaling", "Object cleanup", "Relighting capabilities", "API access available"],
    "Pixlr AI": ["Generative fill feature", "AI background removal", "Smart object selection", "Browser-based editor", "Free professional editing"],
    "Runway": ["Text-to-video generation", "Motion tracking & inpainting", "Green screen removal", "Gen-3 Alpha model", "Professional video tools"],
    "Pika Labs": ["Text-to-video clips", "Smooth motion generation", "Style consistency", "Intuitive interface", "Expressive animation"],
    "HeyGen": ["AI avatar creation", "Multilingual voiceovers", "Custom avatar training", "Template-based videos", "Corporate video focus"],
    "Synthesia": ["120+ language support", "Custom AI avatars", "Professional templates", "Screen recording included", "Enterprise-grade security"],
    "CapCut": ["Auto-captions & subtitles", "Text-to-speech voices", "Background removal", "Mobile-first editing", "Completely free"],
    "Google Veo 3.1": ["Long-form video generation", "Cinematic understanding", "High-quality output", "Google AI research", "Advanced motion physics"],
    "Kling 3.0": ["High-resolution video", "Physical accuracy", "Complex motion handling", "Character interaction", "Realistic physics"],
    "InVideo": ["Text-to-video conversion", "5000+ templates", "Stock media library", "AI voiceovers", "Team collaboration"],
    "Veed.io": ["Auto-subtitles & translation", "Browser-based editing", "Background removal", "Text-to-speech", "No download required"],
    "Wondershare Filmora": ["AI portrait & tracking", "Background removal", "Auto-reframe feature", "Text-to-speech", "Beginner-friendly UI"],
    "Gamma": ["AI-generated presentations", "Interactive web decks", "One-click redesign", "Built-in analytics", "Collaboration ready"],
    "Otter.ai": ["Real-time transcription", "Meeting notes automation", "Action item extraction", "Zoom/Teams integration", "Searchable transcripts"],
    "Motion": ["AI schedule optimization", "Automatic task prioritization", "Calendar integration", "Real-time adjustments", "Team calendar sync"],
    "Fireflies.ai": ["Auto-join meetings", "Speaker identification", "CRM integration", "Transcript search", "Meeting analytics"],
    "Krisp": ["System-level noise cancelation", "Works with any app", "Echo removal", "Background voice removal", "Real-time processing"],
    "Perplexity AI": ["Cited source answers", "Real-time web search", "File upload analysis", "Complex question handling", "Research-focused AI"],
    "Reclaim AI": ["Smart calendar blocking", "Habit scheduling", "Task time allocation", "Google Calendar sync", "Team availability"],
    "Mem": ["AI knowledge organization", "Auto-linking notes", "Smart search retrieval", "Contextual connections", "Workspace integration"],
    "Tome": ["Narrative-driven presentations", "AI research copilot", "Data storytelling", "Interactive formats", "Collaboration tools"],
    "Descript": ["Text-based media editing", "Voice cloning & filler removal", "Screen recording", "Eye contact correction", "Multi-track editing"],
    "Cleanvoice": ["Filler word removal", "Silence compression", "Mouth sound removal", "Multi-language support", "Podcast optimization"],
    "Podcastle": ["All-in-one podcast platform", "Magic Dust audio cleanup", "AI voice generation", "Remote recording", "Publishing tools"],
    "Riverside": ["Local recording technology", "Separate audio/video tracks", "Text-based editing", "AI clip creation", "Studio-quality remote recording"],
    "Auphonic": ["Loudness normalization", "Multi-track processing", "Broadcast standard compliance", "Noise reduction", "Batch processing"],
    "Adobe Podcast": ["Enhance Speech one-click fix", "Web-based recording", "Noise reduction", "Free to use", "Adobe quality"],
    "ElevenLabs": ["Ultra-realistic text-to-speech", "Voice cloning technology", "Speech-to-speech conversion", "Multilingual voices", "Emotional range control"],
    "Murf": ["120+ AI voices", "20+ languages supported", "Voice cloning option", "Video integration", "Pitch & speed control"],
    "Respeecher": ["Hollywood-grade voice cloning", "Emotion-preserving conversion", "Film & TV dubbing", "Voice replacement", "Professional audio quality"],
    "Speechify": ["Multi-platform support", "OCR document scanning", "Natural-sounding voices", "Speed control up to 9x", "Offline listening"],
    "Cursor": ["AI-first code editor", "Multi-file editing", "Codebase understanding", "Inline AI chat", "VS Code compatible"],
    "Claude Code": ["Terminal-native AI coding", "Project-level understanding", "Multi-file refactoring", "Git integration", "Complex engineering tasks"],
    "GitHub Copilot": ["Real-time code suggestions", "Multi-IDE support", "Context-aware completions", "Chat integration", "Millions of users"],
    "Windsurf": ["AI-powered IDE", "Context-aware coding", "Multi-file editing", "Modern UI", "Developer workflow focused"],
    "Replit Agent": ["Full-stack app generation", "Autonomous development", "Deployment included", "Natural language input", "Beginner accessible"],
    "Amazon Q Developer": ["AWS-optimized assistance", "Code generation & security", "AWS service expertise", "Troubleshooting support", "Cloud-native focus"],
    "Sourcegraph Cody": ["Codebase-wide understanding", "Answer from your code", "Multi-repo indexing", "Contextual refactoring", "Enterprise team support"],
    "Tabnine": ["Private/local AI models", "Codebase-trained suggestions", "Offline operation", "Enterprise security", "IDE integration"],
    "Devin": ["Autonomous software engineering", "End-to-end feature building", "Self-contained environment", "Debugging & testing", "Project planning"],
    "Bolt.new": ["Browser-based development", "Complete app generation", "Automatic deployment", "Full-stack support", "No local setup needed"],
    "HubSpot AI": ["CRM-embedded AI", "Predictive lead scoring", "Content generation", "Smart email timing", "Conversational AI"],
    "Semrush AI": ["SEO content writing", "Keyword research AI", "Competitive analysis", "Topic clustering", "Search intelligence"],
    "Surfer SEO": ["Real-time content optimization", "SERP analysis", "Keyword recommendations", "Content score tracking", "Data-driven SEO writing"],
    "Frase.io": ["AI content briefs", "SERP-driven outlines", "AI writing & optimization", "Visibility tracking", "Multi-search monitoring"],
    "Lindy": ["No-code AI assistants", "Custom workflow automation", "Pre-built templates", "API integrations", "Business process AI"],
    "MarketMuse": ["Content gap analysis", "Competitor benchmarking", "Topic modeling AI", "Enterprise content planning", "SEO content scoring"],
    "Zapier AI": ["6000+ app integrations", "AI data extraction", "Smart automation routing", "Content generation workflows", "No-code AI automation"],
    "ActiveCampaign": ["AI predictive sending", "Lead scoring automation", "Customer journey mapping", "Email marketing CRM", "Behavioral segmentation"],
    "Mailchimp AI": ["Predictive segmentation", "Smart send time optimization", "AI content generation", "Automated campaigns", "Small business friendly"],
    "Lately AI": ["Content repurposing AI", "Multi-platform posting", "Social media automation", "Long-form to short-form", "Analytics dashboard"],
    "QuillBot": ["Multiple paraphrasing modes", "Grammar checker included", "Plagiarism detection", "Citation generator", "Summarizer tool"],
    "Wordtune": ["Smart rephrasing engine", "Tone adjustment options", "Expand & shorten text", "Contextual synonyms", "Browser extension"],
    "Hemingway App": ["Readability scoring", "Complex sentence highlighting", "Passive voice detection", "Adverb overuse flagging", "Writing clarity focus"],
    "Scalenut": ["NLP topic clusters", "SEO content briefs", "AI writing with scoring", "Content optimization", "Multi-search engine ready"],
    "Shortly AI": ["Distraction-free editor", "No limits on length", "AI continues your writing", "Minimalist interface", "Long-form focus"],
    "Taskade": ["AI project management", "Mind map creation", "Team collaboration", "AI task generation", "Unified workspace"],
    "Clockwise": ["Focus time protection", "Smart meeting scheduling", "Calendar analytics", "Team time optimization", "Calendar integration"],
    "Todoist AI": ["Natural language input", "Smart task prioritization", "Project suggestions", "Deadline understanding", "Cross-platform sync"],
    "Brevo AI": ["AI send time optimization", "Email & SMS marketing", "Marketing automation", "Built-in CRM", "Affordable pricing"],
    "Buffer AI": ["Content suggestion AI", "Optimal posting schedule", "Multi-platform publishing", "Analytics insights", "Simple interface"],
}

features_es = {
    "Suno AI": ["Canciones completas desde texto", "Soporta múltiples géneros", "Letras, voces e instrumentación", "Generación rápida en segundos", "Nivel gratuito disponible"],
    "Udio": ["Fidelidad de audio excepcional", "Música instrumental realista", "Combinaciones de género complejas", "Nivel gratuito generoso", "Síntesis vocal de alta calidad"],
    "AIVA": ["Composiciones orquestales/cinematográficas", "Entrenado con partituras clásicas", "Creación de bandas sonoras", "Licencia libre de regalías", "Arreglo multipista"],
    "Mubert": ["Generación musical en tiempo real", "Streams adaptativos infinitos", "Libre de regalías", "Control de estado de ánimo", "Enfoque en música electrónica"],
    "Soundraw": ["Edición con supervisión humana", "Regenerar secciones específicas", "Selección de género y estado de ánimo", "Licencia libre de regalías", "Control detallado"],
    "Boomy": ["Creación instantánea de canciones", "Distribución musical global", "Múltiples plantillas de género", "Interfaz para principiantes", "Sin necesidad de teoría musical"],
    "Riffusion": ["Generación basada en espectrogramas", "Edición visual de sonido", "Enfoque experimental con IA", "Base de código abierto", "Manipulación de sonido única"],
    "Beatoven.ai": ["Bandas sonoras basadas en estado de ánimo", "Se adapta a la narrativa del video", "Música libre de regalías", "Edición basada en línea de tiempo", "Diseñado para creadores de video"],
    "LANDR": ["Masterización con IA", "Servicio de distribución musical", "Biblioteca de samples", "Mercado de plugins", "Herramientas de colaboración"],
    "ElevenLabs Music": ["Generación musical con deep learning", "Composiciones con sonido natural", "Versatilidad de género", "Audio de alta calidad", "De la empresa líder en voz IA"],
    "Jasper AI": ["Más de 50 plantillas de contenido", "Personalización de voz de marca", "Modo de escritura SEO", "Colaboración en equipo", "Potenciado por GPT-4"],
    "Writesonic": ["Escritor de artículos IA", "Integración con Chatsonic", "Herramienta de paráfrasis", "Texto a voz", "Precios accesibles"],
    "Copy.ai": ["Automatización de flujos GTM", "Comisiones recurrentes del 45%", "Herramientas de prospección", "Generación de contenido escalable", "Integraciones con CRM"],
    "Rytr": ["Más de 40 casos de uso", "Más de 30 idiomas", "Detector de plagio incluido", "Analizador SEO integrado", "Precio económico"],
    "Sudowrite": ["Story Engine para novelas", "Herramienta Beat Sheet", "Expandir y reescribir prosa", "Desarrollo de personajes", "Lluvia de ideas creativas"],
    "Claude": ["Ventana de contexto de 200K tokens", "IA conversacional matizada", "Capacidades sólidas de razonamiento", "Análisis y generación de código", "Diseño centrado en seguridad"],
    "ChatGPT": ["Entrada de texto, imagen y voz", "Ecosistema de plugins", "Acceso al modelo GPT-4o", "Intérprete de código", "Comunidad masiva de usuarios"],
    "ProWritingAid": ["Más de 20 informes de escritura", "Análisis de estilo y estructura", "Puntuación de legibilidad", "Edición a nivel de manuscrito", "Integración con Word/Google Docs"],
    "Anyword": ["Puntuación predictiva de copy", "Integración con plataformas publicitarias", "Optimización basada en datos", "Analíticas de rendimiento", "IA enfocada en conversión"],
    "Midjourney": ["Calidad artística impresionante", "Interfaz basada en Discord", "Consistencia de estilo", "Salida de alta resolución", "Comunidad creativa activa"],
    "DALL-E 3 / GPT Image": ["Integración perfecta con ChatGPT", "Comprensión de instrucciones complejas", "Generación de imágenes de alta calidad", "Renderizado de texto", "Edición con inpainting"],
    "Adobe Firefly": ["Integración profunda con Creative Cloud", "Relleno y expansión generativa", "Generación de texto a imagen", "Seguridad comercial", "Herramientas de diseño profesionales"],
    "Stable Diffusion": ["Código abierto y local", "Entrenamiento de modelos personalizados", "Sin filtros de contenido", "Extensiones de la comunidad", "Control creativo total"],
    "Leonardo AI": ["Generación en tiempo real", "Entrenamiento de modelos", "Enfoque en activos de juegos", "Estilo consistente", "Biblioteca de estilos predefinidos"],
    "Canva AI": ["Automatización Magic Design", "Generación de copy con Magic Write", "Edición de fotos con IA", "Simplicidad de arrastrar y soltar", "Plantillas para redes sociales"],
    "Ideogram": ["Renderizado de texto líder", "Creación de logotipos y carteles", "Salida fotorrealista", "Control de estilo", "Activos de marca consistentes"],
    "Recraft": ["Modelos IA entrenados con marca", "Estilo consistente en todos los activos", "Salida vectorial y rasterizada", "Enfoque en equipos de marketing", "Control de paleta de colores"],
    "Clipdrop": ["Eliminación de fondo", "Escalado con IA", "Limpieza de objetos", "Reiluminación", "API disponible"],
    "Pixlr AI": ["Relleno generativo", "Eliminación de fondo con IA", "Selección inteligente de objetos", "Editor basado en navegador", "Edición profesional gratuita"],
    "Runway": ["Generación de texto a video", "Seguimiento de movimiento", "Eliminación de fondo verde", "Modelo Gen-3 Alpha", "Herramientas de video profesionales"],
    "Pika Labs": ["Clips de texto a video", "Movimiento suave", "Consistencia de estilo", "Interfaz intuitiva", "Animación expresiva"],
    "HeyGen": ["Creación de avatares IA", "Locuciones multilingües", "Avatares personalizados", "Videos basados en plantillas", "Enfoque en video corporativo"],
    "Synthesia": ["Más de 120 idiomas", "Avatares IA personalizables", "Plantillas profesionales", "Grabación de pantalla incluida", "Seguridad de nivel empresarial"],
    "CapCut": ["Subtítulos automáticos", "Texto a voz", "Eliminación de fondo", "Edición móvil", "Completamente gratuito"],
    "Google Veo 3.1": ["Video de formato largo", "Comprensión cinematográfica", "Salida de alta calidad", "Investigación Google AI", "Física de movimiento avanzada"],
    "Kling 3.0": ["Video de alta resolución", "Precisión física", "Movimiento complejo", "Interacción de personajes", "Física realista"],
    "InVideo": ["Conversión de texto a video", "Más de 5000 plantillas", "Biblioteca de medios", "Locuciones con IA", "Colaboración en equipo"],
    "Veed.io": ["Subtítulos y traducción automáticos", "Edición en navegador", "Eliminación de fondo", "Texto a voz", "Sin descarga necesaria"],
    "Wondershare Filmora": ["AI portrait y seguimiento", "Eliminación de fondo", "Auto-reframe", "Texto a voz", "Interfaz para principiantes"],
    "Gamma": ["Presentaciones generadas por IA", "Decks web interactivos", "Rediseño con un clic", "Analíticas integradas", "Listo para colaboración"],
    "Otter.ai": ["Transcripción en tiempo real", "Notas de reuniones automáticas", "Extracción de elementos de acción", "Integración con Zoom/Teams", "Transcripciones buscables"],
    "Motion": ["Optimización de horarios con IA", "Priorización automática de tareas", "Integración de calendario", "Ajustes en tiempo real", "Sincronización de calendario del equipo"],
    "Fireflies.ai": ["Unión automática a reuniones", "Identificación de hablantes", "Integración con CRM", "Búsqueda en transcripciones", "Analíticas de reuniones"],
    "Krisp": ["Cancelación de ruido a nivel de sistema", "Funciona con cualquier app", "Eliminación de eco", "Eliminación de voces de fondo", "Procesamiento en tiempo real"],
    "Perplexity AI": ["Respuestas con fuentes citadas", "Búsqueda web en tiempo real", "Análisis de archivos", "Preguntas complejas", "IA enfocada en investigación"],
    "Reclaim AI": ["Bloqueo inteligente de calendario", "Programación de hábitos", "Asignación de tiempo a tareas", "Sincronización con Google Calendar", "Disponibilidad del equipo"],
    "Mem": ["Organización de conocimiento con IA", "Auto-enlace de notas", "Búsqueda inteligente", "Conexiones contextuales", "Integración con espacio de trabajo"],
    "Tome": ["Presentaciones narrativas", "Copiloto de investigación IA", "Narración de datos", "Formatos interactivos", "Herramientas de colaboración"],
    "Descript": ["Edición de medios basada en texto", "Clonación de voz", "Grabación de pantalla", "Corrección de contacto visual", "Edición multipista"],
    "Cleanvoice": ["Eliminación de muletillas", "Compresión de silencios", "Eliminación de sonidos bucales", "Soporte multilingüe", "Optimización para podcasts"],
    "Podcastle": ["Plataforma integral de podcasting", "Magic Dust para limpiar audio", "Generación de voz con IA", "Grabación remota", "Herramientas de publicación"],
    "Riverside": ["Grabación local", "Pistas separadas de audio/video", "Edición basada en texto", "Creación de clips con IA", "Grabación remota con calidad de estudio"],
    "Auphonic": ["Normalización de volumen", "Procesamiento multipista", "Cumplimiento de estándares", "Reducción de ruido", "Procesamiento por lotes"],
    "Adobe Podcast": ["Enhance Speech con un clic", "Grabación basada en web", "Reducción de ruido", "Gratuito", "Calidad Adobe"],
    "ElevenLabs": ["Texto a voz ultrarealista", "Clonación de voz", "Conversión de voz a voz", "Voces multilingües", "Control de rango emocional"],
    "Murf": ["Más de 120 voces IA", "Más de 20 idiomas", "Opción de clonación de voz", "Integración de video", "Control de tono y velocidad"],
    "Respeecher": ["Clonación de voz de grado Hollywood", "Conversión con preservación emocional", "Doblaje para cine y TV", "Reemplazo de voz", "Calidad de audio profesional"],
    "Speechify": ["Soporte multiplataforma", "Escaneo OCR de documentos", "Voces con sonido natural", "Control de velocidad hasta 9x", "Escucha sin conexión"],
    "Cursor": ["Editor de código con IA", "Edición multiarchivo", "Comprensión del código base", "Chat de IA integrado", "Compatible con VS Code"],
    "Claude Code": ["Codificación IA nativa en terminal", "Comprensión a nivel de proyecto", "Refactorización multiarchivo", "Integración con Git", "Tareas complejas de ingeniería"],
    "GitHub Copilot": ["Sugerencias de código en tiempo real", "Soporte multi-IDE", "Finalizaciones contextuales", "Chat integrado", "Millones de usuarios"],
    "Windsurf": ["IDE potenciado por IA", "Codificación con contexto", "Edición multiarchivo", "UI moderna", "Enfoque en flujo de trabajo"],
    "Replit Agent": ["Generación de apps full-stack", "Desarrollo autónomo", "Despliegue incluido", "Entrada en lenguaje natural", "Accesible para principiantes"],
    "Amazon Q Developer": ["Asistencia optimizada para AWS", "Generación y seguridad de código", "Experiencia en servicios AWS", "Soporte de solución de problemas", "Enfoque cloud-native"],
    "Sourcegraph Cody": ["Comprensión de todo el código base", "Respuestas de tu código real", "Indexación multi-repo", "Refactorización contextual", "Soporte para equipos empresariales"],
    "Tabnine": ["Modelos de IA privados/locales", "Sugerencias entrenadas con tu código", "Funcionamiento sin conexión", "Seguridad empresarial", "Integración con IDE"],
    "Devin": ["Ingeniería de software autónoma", "Creación de funciones completas", "Entorno autónomo", "Depuración y pruebas", "Planificación de proyectos"],
    "Bolt.new": ["Desarrollo basado en navegador", "Generación de apps completas", "Despliegue automático", "Soporte full-stack", "Sin configuración local"],
    "HubSpot AI": ["IA integrada en CRM", "Puntuación predictiva de leads", "Generación de contenido", "Programación inteligente de emails", "IA conversacional"],
    "Semrush AI": ["Redacción SEO con IA", "Investigación de palabras clave", "Análisis competitivo", "Agrupación de temas", "Inteligencia de búsqueda"],
    "Surfer SEO": ["Optimización de contenido en tiempo real", "Análisis SERP", "Recomendaciones de palabras clave", "Seguimiento de puntuación", "Redacción SEO basada en datos"],
    "Frase.io": ["Briefs de contenido con IA", "Esquemas basados en SERP", "Redacción y optimización IA", "Monitoreo de visibilidad", "Seguimiento multi-buscador"],
    "Lindy": ["Asistentes IA sin código", "Automatización de flujos personalizada", "Plantillas predefinidas", "Integraciones API", "IA para procesos de negocio"],
    "MarketMuse": ["Análisis de brechas de contenido", "Benchmarking competitivo", "Modelado de temas con IA", "Planificación de contenido empresarial", "Puntuación de contenido SEO"],
    "Zapier AI": ["Más de 6000 integraciones", "Extracción de datos con IA", "Enrutamiento inteligente", "Flujos de generación de contenido", "Automatización IA sin código"],
    "ActiveCampaign": ["Envío predictivo con IA", "Automatización de puntuación de leads", "Mapeo de viaje del cliente", "CRM de email marketing", "Segmentación conductual"],
    "Mailchimp AI": ["Segmentación predictiva", "Optimización inteligente de envío", "Generación de contenido IA", "Campañas automatizadas", "Amigable para pequeñas empresas"],
    "Lately AI": ["Reutilización de contenido con IA", "Publicación multiplataforma", "Automatización de redes sociales", "De formato largo a corto", "Panel de analíticas"],
    "QuillBot": ["Múltiples modos de paráfrasis", "Corrector gramatical incluido", "Detección de plagio", "Generador de citas", "Herramienta de resumen"],
    "Wordtune": ["Motor de reformulación inteligente", "Opciones de ajuste de tono", "Expandir y acortar texto", "Sinónimos contextuales", "Extensión de navegador"],
    "Hemingway App": ["Puntuación de legibilidad", "Resaltado de oraciones complejas", "Detección de voz pasiva", "Detección de adverbios", "Enfoque en claridad"],
    "Scalenut": ["Clústeres de temas PLN", "Briefs de contenido SEO", "Redacción IA con puntuación", "Optimización de contenido", "Listo para multi-buscador"],
    "Shortly AI": ["Editor sin distracciones", "Sin límites de longitud", "IA continúa tu escritura", "Interfaz minimalista", "Enfoque en formato largo"],
    "Taskade": ["Gestión de proyectos con IA", "Creación de mapas mentales", "Colaboración en equipo", "Generación de tareas IA", "Espacio de trabajo unificado"],
    "Clockwise": ["Protección de tiempo de enfoque", "Programación inteligente de reuniones", "Analíticas de calendario", "Optimización de tiempo del equipo", "Integración de calendario"],
    "Todoist AI": ["Entrada en lenguaje natural", "Priorización inteligente de tareas", "Sugerencias de proyectos", "Comprensión de plazos", "Sincronización multiplataforma"],
    "Brevo AI": ["Optimización de tiempo de envío", "Email y SMS marketing", "Automatización de marketing", "CRM integrado", "Precios asequibles"],
    "Buffer AI": ["Sugerencias de contenido", "Programación óptima de publicaciones", "Publicación multiplataforma", "Analíticas", "Interfaz simple"],
}

best_for_en = {
    "Suno AI": "Content creators, musicians, and hobbyists who want to generate original songs from text prompts",
    "Udio": "Creators needing high-fidelity AI-generated music with realistic instrumental quality",
    "AIVA": "Game developers and filmmakers seeking custom orchestral and cinematic soundtracks",
    "Mubert": "Streamers and content creators wanting endless royalty-free electronic background music",
    "Soundraw": "Content creators who want hands-on control over AI music generation",
    "Boomy": "Complete beginners who want to create and release original music in minutes",
    "Riffusion": "Tech-savvy musicians and experimenters interested in visual AI music synthesis",
    "Beatoven.ai": "YouTubers and podcasters needing adaptive mood-based background music",
    "LANDR": "Independent musicians looking for AI mastering, distribution, and production tools",
    "ElevenLabs Music": "Content creators needing natural-sounding AI-generated music from a trusted voice AI brand",
    "Jasper AI": "Marketing teams and content professionals who need scalable, on-brand content production",
    "Writesonic": "Solopreneurs and small businesses wanting affordable, versatile AI writing",
    "Copy.ai": "Go-to-market teams automating content creation and sales outreach at scale",
    "Rytr": "Freelancers and startups needing budget-friendly AI writing across multiple languages",
    "Sudowrite": "Novelists, screenwriters, and creative writers working on long-form projects",
    "Claude": "Professionals needing nuanced analysis, coding help, and thoughtful AI conversations",
    "ChatGPT": "Anyone needing a versatile, all-purpose AI assistant for writing, coding, and problem-solving",
    "ProWritingAid": "Authors and editors who need deep manuscript analysis beyond basic grammar checking",
    "Anyword": "Performance marketers who want data-driven copy optimized for conversions",
    "Midjourney": "Artists and designers prioritizing artistic quality and visual beauty in AI imagery",
    "DALL-E 3 / GPT Image": "ChatGPT users who want seamless text-to-image generation in one workflow",
    "Adobe Firefly": "Designers already in the Adobe ecosystem needing generative AI features",
    "Stable Diffusion": "Developers and power users wanting full control over AI image generation without restrictions",
    "Leonardo AI": "Game developers and concept artists needing consistent, trainable AI image generation",
    "Canva AI": "Non-designers and social media creators who want AI design tools in a simple interface",
    "Ideogram": "Designers creating logos, posters, and graphics where text legibility is critical",
    "Recraft": "Marketing teams producing large volumes of on-brand visual content",
    "Clipdrop": "Content creators needing fast, reliable AI image cleanup and enhancement tools",
    "Pixlr AI": "Anyone needing free, browser-based professional photo editing with AI features",
    "Runway": "Professional video editors and filmmakers exploring cutting-edge AI video tools",
    "Pika Labs": "Content creators exploring accessible AI video generation with smooth results",
    "HeyGen": "Corporate teams creating professional AI avatar videos for training and marketing",
    "Synthesia": "Enterprises needing scalable AI video production with custom avatars and multilingual support",
    "CapCut": "Social media creators wanting a powerful, free video editor with AI features",
    "Google Veo 3.1": "Researchers and early adopters exploring state-of-the-art AI video generation",
    "Kling 3.0": "Creators needing high-resolution AI video with physically accurate motion",
    "InVideo": "Marketers and businesses creating professional videos at scale without technical expertise",
    "Veed.io": "Social media creators and educators needing quick, browser-based video editing",
    "Wondershare Filmora": "YouTubers and content creators wanting powerful editing without professional complexity",
    "Gamma": "Professionals who want beautiful, interactive presentations created in minutes",
    "Otter.ai": "Teams wanting automated meeting notes, transcripts, and action item extraction",
    "Motion": "Busy professionals who need AI-optimized scheduling and task prioritization",
    "Fireflies.ai": "Sales teams and managers who need to capture and analyze meeting conversations",
    "Krisp": "Remote workers and professionals who take calls from noisy environments",
    "Perplexity AI": "Researchers and professionals needing cited, real-time answers to complex questions",
    "Reclaim AI": "Busy professionals wanting AI-optimized calendar scheduling and habit tracking",
    "Mem": "Knowledge workers who accumulate large amounts of information needing smart retrieval",
    "Tome": "Consultants and analysts building data-driven, narrative presentations",
    "Descript": "Podcasters and video creators wanting text-based editing and AI-powered production",
    "Cleanvoice": "Podcasters wanting automated audio cleanup without manual editing",
    "Podcastle": "Podcasters wanting an all-in-one platform from recording to publishing",
    "Riverside": "Podcasters and content creators needing studio-quality remote recordings",
    "Auphonic": "Podcasters and audio producers wanting broadcast-standard automated audio processing",
    "Adobe Podcast": "Beginner podcasters wanting free, one-click audio enhancement",
    "ElevenLabs": "Content creators, game developers, and enterprises needing professional-grade AI voice synthesis",
    "Murf": "E-learning creators and marketers needing natural AI voiceovers for videos",
    "Respeecher": "Film and TV studios needing Hollywood-grade voice cloning and dubbing",
    "Speechify": "Students and professionals wanting to consume written content hands-free",
    "Cursor": "Developers who want deep AI integration in their code editor",
    "Claude Code": "Developers preferring terminal-based AI coding assistance for complex projects",
    "GitHub Copilot": "Developers of all levels wanting real-time AI code suggestions in their IDE",
    "Windsurf": "Developers wanting a modern AI-powered IDE with deep context awareness",
    "Replit Agent": "Beginners and rapid prototypers who want to build apps through conversation",
    "Amazon Q Developer": "AWS developers needing AI assistance optimized for cloud-native development",
    "Sourcegraph Cody": "Development teams working with large, multi-repository codebases",
    "Tabnine": "Enterprise teams needing private, offline AI code completion with security compliance",
    "Devin": "Teams wanting autonomous AI software engineering for end-to-end feature development",
    "Bolt.new": "Non-developers and rapid prototypers wanting to build web apps without local setup",
    "HubSpot AI": "Businesses using HubSpot who want AI embedded throughout their CRM",
    "Semrush AI": "SEO professionals and marketers needing AI-enhanced search marketing insights",
    "Surfer SEO": "Content creators focused on data-driven SEO writing and SERP optimization",
    "Frase.io": "SEO content teams wanting AI-powered research, writing, and visibility tracking",
    "Lindy": "Teams wanting to automate business workflows with custom no-code AI assistants",
    "MarketMuse": "Enterprise content teams needing AI-driven content strategy and competitive analysis",
    "Zapier AI": "Anyone using Zapier who wants to add AI capabilities to their automated workflows",
    "ActiveCampaign": "Businesses wanting sophisticated marketing automation without enterprise complexity",
    "Mailchimp AI": "Small businesses wanting accessible AI-powered email marketing automation",
    "Lately AI": "Marketers managing multiple social channels who want automated content repurposing",
    "QuillBot": "Students and ESL professionals needing paraphrasing, grammar, and plagiarism tools",
    "Wordtune": "Writers wanting to refine and improve existing text with smart rephrasing",
    "Hemingway App": "Writers focused on making their prose clearer, simpler, and more readable",
    "Scalenut": "Content teams creating data-driven SEO strategies at scale",
    "Shortly AI": "Writers wanting a minimalist, distraction-free AI writing environment for long-form content",
    "Taskade": "Remote teams wanting an all-in-one workspace with AI-powered productivity tools",
    "Clockwise": "Teams wanting to reduce meeting overload and protect deep work time",
    "Todoist AI": "Individuals wanting smarter task management with natural language and AI prioritization",
    "Brevo AI": "Growing businesses wanting affordable, comprehensive AI-powered marketing",
    "Buffer AI": "Solopreneurs and small businesses wanting simple AI-powered social media scheduling",
}

best_for_es = {
    "Suno AI": "Creadores de contenido y músicos que quieren generar canciones originales desde texto",
    "Udio": "Creadores que necesitan música generada por IA de alta fidelidad con calidad instrumental realista",
    "AIVA": "Desarrolladores de juegos y cineastas que buscan bandas sonoras orquestales personalizadas",
    "Mubert": "Streamers y creadores que quieren música electrónica de fondo libre de regalías",
    "Soundraw": "Creadores que quieren control práctico sobre la generación musical con IA",
    "Boomy": "Principiantes que quieren crear y lanzar música original en minutos",
    "Riffusion": "Músicos con conocimientos técnicos interesados en síntesis musical visual con IA",
    "Beatoven.ai": "YouTubers y podcasters que necesitan música de fondo adaptable basada en estado de ánimo",
    "LANDR": "Músicos independientes que buscan masterización, distribución y producción musical con IA",
    "ElevenLabs Music": "Creadores que necesitan música generada por IA con sonido natural de una marca confiable",
    "Jasper AI": "Equipos de marketing y profesionales del contenido que necesitan producción escalable",
    "Writesonic": "Autónomos y pequeñas empresas que quieren redacción IA versátil y asequible",
    "Copy.ai": "Equipos GTM que automatizan creación de contenido y prospección de ventas a escala",
    "Rytr": "Autónomos y startups que necesitan redacción IA económica en múltiples idiomas",
    "Sudowrite": "Novelistas, guionistas y escritores creativos que trabajan en proyectos de formato largo",
    "Claude": "Profesionales que necesitan análisis matizados, ayuda con código y conversaciones IA reflexivas",
    "ChatGPT": "Cualquiera que necesite un asistente IA versátil para escribir, programar y resolver problemas",
    "ProWritingAid": "Autores y editores que necesitan análisis profundo de manuscritos más allá de la gramática",
    "Anyword": "Especialistas en marketing de rendimiento que quieren copy optimizado para conversiones",
    "Midjourney": "Artistas y diseñadores que priorizan la calidad artística en imágenes generadas por IA",
    "DALL-E 3 / GPT Image": "Usuarios de ChatGPT que quieren generación de imágenes integrada en un solo flujo",
    "Adobe Firefly": "Diseñadores en el ecosistema Adobe que necesitan funciones de IA generativa",
    "Stable Diffusion": "Desarrolladores y usuarios avanzados que quieren control total sobre generación de imágenes",
    "Leonardo AI": "Desarrolladores de juegos y artistas conceptuales que necesitan generación de imágenes consistente",
    "Canva AI": "No diseñadores y creadores de redes sociales que quieren herramientas de IA en una interfaz simple",
    "Ideogram": "Diseñadores que crean logotipos y gráficos donde la legibilidad del texto es crítica",
    "Recraft": "Equipos de marketing que producen grandes volúmenes de contenido visual de marca",
    "Clipdrop": "Creadores que necesitan herramientas rápidas y confiables de limpieza y mejora de imágenes",
    "Pixlr AI": "Cualquiera que necesite edición de fotos profesional gratuita en navegador con funciones IA",
    "Runway": "Editores de video profesionales que exploran herramientas de video con IA de vanguardia",
    "Pika Labs": "Creadores que exploran generación de video con IA accesible con resultados suaves",
    "HeyGen": "Equipos corporativos que crean videos profesionales con avatares IA para capacitación y marketing",
    "Synthesia": "Empresas que necesitan producción de video IA escalable con avatares personalizados",
    "CapCut": "Creadores de redes sociales que quieren un editor de video potente y gratuito con IA",
    "Google Veo 3.1": "Investigadores y early adopters que exploran generación de video con IA de vanguardia",
    "Kling 3.0": "Creadores que necesitan video IA de alta resolución con movimiento físicamente preciso",
    "InVideo": "Profesionales del marketing que crean videos profesionales a escala sin experiencia técnica",
    "Veed.io": "Creadores de redes sociales y educadores que necesitan edición de video rápida en navegador",
    "Wondershare Filmora": "YouTubers que quieren edición potente sin complejidad profesional",
    "Gamma": "Profesionales que quieren presentaciones interactivas hermosas creadas en minutos",
    "Otter.ai": "Equipos que quieren notas de reuniones y transcripciones automáticas",
    "Motion": "Profesionales ocupados que necesitan programación optimizada y priorización de tareas con IA",
    "Fireflies.ai": "Equipos de ventas que necesitan capturar y analizar conversaciones de reuniones",
    "Krisp": "Trabajadores remotos que toman llamadas desde entornos ruidosos",
    "Perplexity AI": "Investigadores y profesionales que necesitan respuestas citadas a preguntas complejas",
    "Reclaim AI": "Profesionales ocupados que quieren optimización de calendario y seguimiento de hábitos con IA",
    "Mem": "Trabajadores del conocimiento que acumulan información y necesitan recuperación inteligente",
    "Tome": "Consultores y analistas que crean presentaciones narrativas basadas en datos",
    "Descript": "Podcasters y creadores de video que quieren edición basada en texto y producción con IA",
    "Cleanvoice": "Podcasters que quieren limpieza de audio automatizada sin edición manual",
    "Podcastle": "Podcasters que quieren una plataforma integral desde grabación hasta publicación",
    "Riverside": "Podcasters que necesitan grabaciones remotas con calidad de estudio",
    "Auphonic": "Productores de audio que quieren procesamiento automatizado con estándar de transmisión",
    "Adobe Podcast": "Podcasters principiantes que quieren mejora de audio gratuita con un clic",
    "ElevenLabs": "Creadores y empresas que necesitan síntesis de voz IA de grado profesional",
    "Murf": "Creadores de e-learning y especialistas en marketing que necesitan locuciones IA naturales",
    "Respeecher": "Estudios de cine y TV que necesitan clonación de voz y doblaje de grado profesional",
    "Speechify": "Estudiantes y profesionales que quieren consumir contenido escrito sin usar las manos",
    "Cursor": "Desarrolladores que quieren integración profunda de IA en su editor de código",
    "Claude Code": "Desarrolladores que prefieren asistencia de codificación IA en terminal para proyectos complejos",
    "GitHub Copilot": "Desarrolladores de todos los niveles que quieren sugerencias de código IA en tiempo real",
    "Windsurf": "Desarrolladores que quieren un IDE moderno con IA y comprensión profunda del contexto",
    "Replit Agent": "Principiantes y prototipadores rápidos que quieren crear apps mediante conversación",
    "Amazon Q Developer": "Desarrolladores AWS que necesitan asistencia IA optimizada para desarrollo cloud-native",
    "Sourcegraph Cody": "Equipos de desarrollo que trabajan con bases de código grandes y multi-repositorio",
    "Tabnine": "Equipos empresariales que necesitan finalización de código IA privada y sin conexión",
    "Devin": "Equipos que quieren ingeniería de software autónoma para desarrollo de funciones completas",
    "Bolt.new": "No desarrolladores y prototipadores que quieren crear apps web sin configuración local",
    "HubSpot AI": "Empresas que usan HubSpot y quieren IA integrada en todo su CRM",
    "Semrush AI": "Profesionales SEO que necesitan información mejorada por IA para marketing de búsqueda",
    "Surfer SEO": "Creadores de contenido enfocados en redacción SEO basada en datos y optimización SERP",
    "Frase.io": "Equipos de contenido SEO que quieren investigación, redacción y monitoreo con IA",
    "Lindy": "Equipos que quieren automatizar flujos de trabajo con asistentes IA sin código",
    "MarketMuse": "Equipos de contenido empresarial que necesitan estrategia de contenido con IA",
    "Zapier AI": "Cualquiera que use Zapier y quiera añadir capacidades de IA a sus flujos automatizados",
    "ActiveCampaign": "Empresas que quieren automatización de marketing sofisticada sin complejidad empresarial",
    "Mailchimp AI": "Pequeñas empresas que quieren automatización de email marketing con IA accesible",
    "Lately AI": "Especialistas en marketing que gestionan múltiples canales sociales y quieren reutilización automatizada",
    "QuillBot": "Estudiantes y profesionales ESL que necesitan paráfrasis, gramática y detección de plagio",
    "Wordtune": "Escritores que quieren refinar texto existente con reformulación inteligente",
    "Hemingway App": "Escritores enfocados en hacer su prosa más clara, simple y legible",
    "Scalenut": "Equipos de contenido que crean estrategias SEO basadas en datos a escala",
    "Shortly AI": "Escritores que quieren un entorno minimalista sin distracciones para contenido de formato largo",
    "Taskade": "Equipos remotos que quieren un espacio de trabajo integral con herramientas de productividad IA",
    "Clockwise": "Equipos que quieren reducir la sobrecarga de reuniones y proteger el tiempo de trabajo profundo",
    "Todoist AI": "Personas que quieren gestión de tareas más inteligente con lenguaje natural y priorización IA",
    "Brevo AI": "Empresas en crecimiento que quieren marketing integral con IA a precio asequible",
    "Buffer AI": "Autónomos y pequeñas empresas que quieren programación de redes sociales simple con IA",
}

pricing_note_en = {
    "Suno AI": "Free tier available with daily credits; Pro plan at $10/mo for unlimited generations and commercial rights",
    "Udio": "Free tier with generous daily credits; Pro plan at $10/mo for unlimited generations and priority queue",
    "AIVA": "Free tier with limited downloads; subscription plans start at $15/mo for unlimited compositions and commercial licensing",
    "Mubert": "Free tier with watermarked tracks; Pro plans start at $12/mo for royalty-free music and commercial use",
    "Soundraw": "Free tier with limited downloads; Creator plan at $16.99/mo for unlimited royalty-free music",
    "Boomy": "Free tier with basic features; Boomy Pro at $9.99/mo for unlimited releases and distribution",
    "Riffusion": "Free for basic use on web interface; advanced features and API access available through paid plans",
    "Beatoven.ai": "Free tier with 15 minutes of music; paid plans start at $6/mo for more minutes and features",
    "LANDR": "Free mastering preview; subscription plans start at $12.99/mo for unlimited mastering and distribution",
    "ElevenLabs Music": "Available through ElevenLabs subscription; plans start at $5/mo for basic access to music generation",
    "Jasper AI": "Creator plan at $49/mo for 1 user; Pro plan at $69/mo with brand voice and collaboration; custom Business plans available",
    "Writesonic": "Free tier with limited words; Individual plan at $16/mo for 50K words; Enterprise plan for teams",
    "Copy.ai": "Free tier with 2K words; Pro plan at $49/mo for unlimited words and workflow automation; Team plan at $249/mo",
    "Rytr": "Free plan with 10K characters/mo; Saver at $9/mo for 100K chars; Unlimited at $29/mo for unlimited generations",
    "Sudowrite": "Hobby at $19/mo for 30K words; Professional at $29/mo for 50K words; Max at $59/mo for 100K words",
    "Claude": "Free tier with limited usage; Pro plan at $20/mo for expanded access; Team at $25/user/mo for organizations",
    "ChatGPT": "Free tier available; ChatGPT Plus at $20/mo for GPT-4o access, DALL-E, and advanced features; Team at $25/user/mo",
    "ProWritingAid": "Free with limited reports; Premium at $30/mo for full reports and 50 summaries; Premium Pro at $42/mo",
    "Anyword": "Free tier with basic scoring; Starter at $49/mo; Data-Driven at $99/mo; Business at $499/mo for teams",
    "Midjourney": "Basic at $10/mo for 3.3 hours GPU time; Standard at $30/mo; Pro at $60/mo; Mega at $120/mo",
    "DALL-E 3 / GPT Image": "Available through ChatGPT Plus ($20/mo) or OpenAI API with pay-per-image pricing",
    "Adobe Firefly": "Included with Creative Cloud subscription at $54.99/mo; free tier with 25 monthly generative credits",
    "Stable Diffusion": "Free and open-source (local); cloud services available through Stability AI API with usage-based pricing",
    "Leonardo AI": "Free tier with daily tokens; Apprentice at $10/mo for more tokens; Artisan at $28/mo; Maestro at $59/mo",
    "Canva AI": "Free tier with limited AI features; Pro at $12.99/mo for full AI access, premium templates, and brand kits",
    "Ideogram": "Free tier with limited generations; Basic at $20/mo for 2K fast gens; Advanced at $40/mo for 5K fast gens",
    "Recraft": "Free tier with 200 generations; Pro at $19/mo for unlimited and custom model training; Team at custom pricing",
    "Clipdrop": "Free tier with basic tools; Pro at $9/mo for high-resolution output and API access",
    "Pixlr AI": "Free tier with ads and basic features; Pixlr Premium at $7.99/mo for AI tools and no ads",
    "Runway": "Free tier with limited exports; Standard at $15/mo for 5 exports; Pro at $35/mo; Unlimited at $95/mo",
    "Pika Labs": "Free tier with limited generation; Standard at $10/mo for more credits; Unlimited at $36/mo for priority generation",
    "HeyGen": "Free tier with 5 min video generation; Creator at $29/mo for 30 min; Business at $89/mo for 60 min",
    "Synthesia": "Starter at $29/mo for 10 video mins; Creator at $89/mo for 30 mins; Enterprise with custom pricing",
    "CapCut": "Completely free with all AI features; Pro plan at $7.99/mo for advanced cloud features and premium assets",
    "Google Veo 3.1": "Available through Google Cloud's Vertex AI with usage-based pricing; limited public access during research phase",
    "Kling 3.0": "Available through Kuaishou platform with credit-based pricing; details vary by region",
    "InVideo": "Free tier with watermarked exports; Plus at $25/mo for 5 exports; Max at $60/mo for 20 exports",
    "Veed.io": "Free tier with watermarked exports; Basic at $18/mo for 30 min export; Pro at $30/mo; Business at $59/mo",
    "Wondershare Filmora": "One-time purchase at $49.99; Annual plan at $49.99/yr; Perpetual plan at $79.99 with updates",
    "Gamma": "Free tier with limited cards; Pro at $10/mo for unlimited; Team at $20/mo for collaboration features",
    "Otter.ai": "Free tier with 300 min/mo; Pro at $16.99/mo for 1,200 min; Business at $30/user/mo for advanced features",
    "Motion": "Free tier with basic AI scheduling; Pro at $19/mo for individuals; Team at custom pricing",
    "Fireflies.ai": "Free tier with 800 min storage; Pro at $18/mo for 8,000 min; Business at $29/mo; Enterprise at custom",
    "Krisp": "Free tier with 60 min/day; Pro at $10/mo for unlimited; Team at $15/user/mo with management features",
    "Perplexity AI": "Free tier with limited searches; Pro at $20/mo for unlimited, file uploads, and API access",
    "Reclaim AI": "Free tier with basic scheduling; Lite at $10/mo; Pro at $15/mo; Business at $25/user/mo",
    "Mem": "Free tier with limited notes; Pro at $14.99/mo for 10K notes and AI features; Team at $25/user/mo",
    "Tome": "Free tier with limited presentations; Pro at $16/mo for unlimited and advanced AI features",
    "Descript": "Free tier with limited exports; Hobbyist at $24/mo for 10 hrs transcription; Pro at $40/mo for 30 hrs",
    "Cleanvoice": "Pay-as-you-go: $0.10/min; Monthly plans start at $10/mo for 100 min of processing",
    "Podcastle": "Free tier with basic features; Storyteller at $14.99/mo for 5 hrs recording; Pro at $29.99/mo for 20 hrs",
    "Riverside": "Free tier with 2 hrs recording; Pro at $24/mo for 6 hrs; Business at $34/mo for 12 hrs",
    "Auphonic": "Free tier with 2 hrs/mo; Pro at $15/mo for 10 hrs; Business at $35/mo for 25 hrs",
    "Adobe Podcast": "Completely free web-based tool; requires Adobe account but no Creative Cloud subscription needed",
    "ElevenLabs": "Free tier with 10K chars/mo; Starter at $5/mo for 30K; Creator at $22/mo for 100K; Pro at $99/mo",
    "Murf": "Free tier with limited voiceovers; Creator at $29/mo for 24 hrs; Business at $79/mo for 48 hrs",
    "Respeecher": "Custom pricing based on project scope and volume; primarily serves enterprise and entertainment clients",
    "Speechify": "Free tier with limited voices; Premium at $11.58/mo for 20+ voices and 4x speed; Audiobook plans available",
    "Cursor": "Free tier with limited AI usage; Pro at $20/mo for 500 fast requests; Business at $40/user/mo",
    "Claude Code": "Included with Claude Pro ($20/mo) or Team ($25/user/mo); usage limits based on subscription tier",
    "GitHub Copilot": "Free tier with limited completions; Teams at $4/user/mo; Enterprise at $21/user/mo",
    "Windsurf": "Free tier with basic AI features; Windsurf Pro at $15/mo for unlimited AI commands and flow mode",
    "Replit Agent": "Free tier with limited cycles; Core at $25/mo for more compute; Teams with custom pricing",
    "Amazon Q Developer": "Free tier with basic features; Pro at $19/user/mo for advanced capabilities and AWS expertise",
    "Sourcegraph Cody": "Free tier with limited requests; Pro at $9/mo for unlimited; Enterprise with custom pricing",
    "Tabnine": "Free tier with basic completions; Pro at $12/mo for whole-line; Enterprise at custom pricing for private deployment",
    "Devin": "Available through subscription; pricing details through Cognition Labs for team and enterprise plans",
    "Bolt.new": "Free tier with limited tokens; Pro at $20/mo for more usage; Teams with custom pricing",
    "HubSpot AI": "AI features included with HubSpot subscriptions; Free CRM with limited AI; paid plans start at $45/mo",
    "Semrush AI": "Pro at $139.95/mo for SEO toolkit; Guru at $249.95/mo; Business at $499.95/mo; AI features included in plans",
    "Surfer SEO": "Essential at $89/mo for 10 articles; Advanced at $159/mo for 20; Max at $279/mo for 40 articles",
    "Frase.io": "Free tier with 1 article/mo; Basic at $14.99/mo for 4 articles; Team at $49.99/mo for 20 articles",
    "Lindy": "Free tier with basic automations; Pro at $15/mo for more workflows; Team at $30/mo for collaboration",
    "MarketMuse": "Custom pricing based on content volume and team size; typically starts at several hundred dollars per month",
    "Zapier AI": "AI features included in Zapier plans; Free tier with limited tasks; Starter at $29.99/mo; Professional at $73.50/mo",
    "ActiveCampaign": "Starts at $15/mo for email marketing; Plus at $49/mo for automation; Professional at $79/mo for advanced features",
    "Mailchimp AI": "Free tier for up to 500 contacts; Essentials at $13/mo; Standard at $20/mo; Premium at $350/mo",
    "Lately AI": "Free tier with limited posts; Pro at $39/mo for more content; Business at $79/mo for teams",
    "QuillBot": "Free tier with limited words; Premium at $8.33/mo (billed annually) for unlimited words and all modes",
    "Wordtune": "Free tier with limited rewrites; Premium at $9.99/mo for unlimited; Unlimited at $14.99/mo for advanced AI",
    "Hemingway App": "Free web version; Desktop app at $19.99 one-time purchase for offline use",
    "Scalenut": "Essential at $39/mo for 10 articles; Growth at $79/mo for 30; Pro at $149/mo for 80 articles",
    "Shortly AI": "Monthly plan at $11/mo for unlimited writing; Annual plan at $65/yr for discounted rate",
    "Taskade": "Free tier with basic features; Pro at $8/mo for AI features; Business at $16/mo for team collaboration",
    "Clockwise": "Free tier with basic features; Pro at $12.50/mo for unlimited; Enterprise at custom pricing",
    "Todoist AI": "Free tier with basic features; Pro at $5/mo for AI features and productivity insights",
    "Brevo AI": "Free tier with 300 emails/day; Starter at $9/mo for 20K emails; Business at $25/mo for unlimited contacts",
    "Buffer AI": "Free tier with 3 channels; Essentials at $6/mo per channel; Team at $12/mo per channel for collaboration",
}

pricing_note_es = {
    "Suno AI": "Nivel gratuito con créditos diarios; Plan Pro a $10/mes para generaciones ilimitadas y derechos comerciales",
    "Udio": "Nivel gratuito con créditos diarios generosos; Plan Pro a $10/mes para generaciones ilimitadas",
    "AIVA": "Nivel gratuito con descargas limitadas; Planes desde $15/mes para composiciones ilimitadas y licencia comercial",
    "Mubert": "Nivel gratuito con marcas de agua; Planes Pro desde $12/mes para música libre de regalías",
    "Soundraw": "Nivel gratuito con descargas limitadas; Plan Creator a $16.99/mes para música ilimitada libre de regalías",
    "Boomy": "Nivel gratuito con funciones básicas; Boomy Pro a $9.99/mes para lanzamientos ilimitados",
    "Riffusion": "Gratuito para uso básico en web; funciones avanzadas disponibles en planes de pago",
    "Beatoven.ai": "Nivel gratuito con 15 minutos de música; planes desde $6/mes para más minutos",
    "LANDR": "Vista previa de masterización gratuita; planes desde $12.99/mes para masterización y distribución ilimitadas",
    "ElevenLabs Music": "Disponible con suscripción a ElevenLabs; planes desde $5/mes para acceso básico",
    "Jasper AI": "Plan Creator a $49/mes; Plan Pro a $69/mes con voz de marca; Planes Business personalizados",
    "Writesonic": "Nivel gratuito con palabras limitadas; Plan Individual a $16/mes para 50K palabras",
    "Copy.ai": "Nivel gratuito con 2K palabras; Plan Pro a $49/mes; Plan Team a $249/mes",
    "Rytr": "Plan gratuito con 10K caracteres/mes; Saver a $9/mes; Unlimited a $29/mes",
    "Sudowrite": "Hobby a $19/mes por 30K palabras; Professional a $29/mes; Max a $59/mes",
    "Claude": "Nivel gratuito; Plan Pro a $20/mes; Team a $25/usuario/mes para organizaciones",
    "ChatGPT": "Nivel gratuito disponible; ChatGPT Plus a $20/mes con GPT-4o; Team a $25/usuario/mes",
    "ProWritingAid": "Gratuito con informes limitados; Premium a $30/mes; Premium Pro a $42/mes",
    "Anyword": "Nivel gratuito; Starter a $49/mes; Data-Driven a $99/mes; Business a $499/mes",
    "Midjourney": "Basic a $10/mes; Standard a $30/mes; Pro a $60/mes; Mega a $120/mes",
    "DALL-E 3 / GPT Image": "Disponible con ChatGPT Plus ($20/mes) o API de OpenAI con pago por imagen",
    "Adobe Firefly": "Incluido con Creative Cloud ($54.99/mes); nivel gratuito con 25 créditos mensuales",
    "Stable Diffusion": "Gratuito y de código abierto (local); servicios cloud disponibles con API de Stability AI",
    "Leonardo AI": "Nivel gratuito con tokens diarios; Apprentice a $10/mes; Artisan a $28/mes; Maestro a $59/mes",
    "Canva AI": "Nivel gratuito con funciones IA limitadas; Pro a $12.99/mes para acceso completo",
    "Ideogram": "Nivel gratuito; Basic a $20/mes; Advanced a $40/mes para más generaciones rápidas",
    "Recraft": "Nivel gratuito con 200 generaciones; Pro a $19/mes para ilimitado; Team con precio personalizado",
    "Clipdrop": "Nivel gratuito; Pro a $9/mes para alta resolución y acceso API",
    "Pixlr AI": "Nivel gratuito con anuncios; Pixlr Premium a $7.99/mes sin anuncios y herramientas IA",
    "Runway": "Nivel gratuito; Standard a $15/mes; Pro a $35/mes; Unlimited a $95/mes",
    "Pika Labs": "Nivel gratuito; Standard a $10/mes; Unlimited a $36/mes para generación prioritaria",
    "HeyGen": "Nivel gratuito con 5 min de video; Creator a $29/mes; Business a $89/mes",
    "Synthesia": "Starter a $29/mes por 10 min; Creator a $89/mes por 30 min; Enterprise con precio personalizado",
    "CapCut": "Completamente gratuito; Plan Pro a $7.99/mes para funciones cloud avanzadas",
    "Google Veo 3.1": "Disponible a través de Google Cloud Vertex AI; acceso público limitado durante investigación",
    "Kling 3.0": "Disponible en plataforma Kuaishou con precios basados en créditos; varía por región",
    "InVideo": "Nivel gratuito con marca de agua; Plus a $25/mes; Max a $60/mes",
    "Veed.io": "Nivel gratuito; Basic a $18/mes; Pro a $30/mes; Business a $59/mes",
    "Wondershare Filmora": "Compra única a $49.99; Plan anual a $49.99/año; Plan perpetuo a $79.99",
    "Gamma": "Nivel gratuito; Pro a $10/mes; Team a $20/mes para colaboración",
    "Otter.ai": "Nivel gratuito con 300 min/mes; Pro a $16.99/mes; Business a $30/usuario/mes",
    "Motion": "Nivel gratuito; Pro a $19/mes para individuos; Team con precio personalizado",
    "Fireflies.ai": "Nivel gratuito con 800 min; Pro a $18/mes; Business a $29/mes; Enterprise personalizado",
    "Krisp": "Nivel gratuito con 60 min/día; Pro a $10/mes; Team a $15/usuario/mes",
    "Perplexity AI": "Nivel gratuito; Pro a $20/mes para ilimitado, carga de archivos y acceso API",
    "Reclaim AI": "Nivel gratuito; Lite a $10/mes; Pro a $15/mes; Business a $25/usuario/mes",
    "Mem": "Nivel gratuito; Pro a $14.99/mes; Team a $25/usuario/mes",
    "Tome": "Nivel gratuito; Pro a $16/mes para ilimitado y funciones IA avanzadas",
    "Descript": "Nivel gratuito; Hobbyist a $24/mes; Pro a $40/mes para más horas de transcripción",
    "Cleanvoice": "Pago por uso: $0.10/min; Planes mensuales desde $10/mes por 100 min",
    "Podcastle": "Nivel gratuito; Storyteller a $14.99/mes; Pro a $29.99/mes",
    "Riverside": "Nivel gratuito con 2 hrs; Pro a $24/mes; Business a $34/mes",
    "Auphonic": "Nivel gratuito con 2 hrs/mes; Pro a $15/mes; Business a $35/mes",
    "Adobe Podcast": "Completamente gratuito; solo requiere cuenta Adobe sin suscripción a Creative Cloud",
    "ElevenLabs": "Nivel gratuito con 10K chars/mes; Starter a $5/mes; Creator a $22/mes; Pro a $99/mes",
    "Murf": "Nivel gratuito; Creator a $29/mes; Business a $79/mes",
    "Respeecher": "Precio personalizado según proyecto; principalmente para clientes empresariales y de entretenimiento",
    "Speechify": "Nivel gratuito; Premium a $11.58/mes para 20+ voces; Planes de audiolibros disponibles",
    "Cursor": "Nivel gratuito; Pro a $20/mes; Business a $40/usuario/mes",
    "Claude Code": "Incluido con Claude Pro ($20/mes) o Team ($25/usuario/mes)",
    "GitHub Copilot": "Nivel gratuito; Teams a $4/usuario/mes; Enterprise a $21/usuario/mes",
    "Windsurf": "Nivel gratuito; Windsurf Pro a $15/mes para comandos IA ilimitados",
    "Replit Agent": "Nivel gratuito; Core a $25/mes; Teams con precio personalizado",
    "Amazon Q Developer": "Nivel gratuito; Pro a $19/usuario/mes para funciones avanzadas",
    "Sourcegraph Cody": "Nivel gratuito; Pro a $9/mes; Enterprise con precio personalizado",
    "Tabnine": "Nivel gratuito; Pro a $12/mes; Enterprise con precio personalizado para despliegue privado",
    "Devin": "Disponible por suscripción; precios a través de Cognition Labs para equipos y empresas",
    "Bolt.new": "Nivel gratuito; Pro a $20/mes; Teams con precio personalizado",
    "HubSpot AI": "Funciones IA incluidas con suscripciones HubSpot; CRM gratuito con IA limitada; planes desde $45/mes",
    "Semrush AI": "Pro a $139.95/mes; Guru a $249.95/mes; Business a $499.95/mes; IA incluida en todos los planes",
    "Surfer SEO": "Essential a $89/mes; Advanced a $159/mes; Max a $279/mes",
    "Frase.io": "Nivel gratuito con 1 artículo/mes; Basic a $14.99/mes; Team a $49.99/mes",
    "Lindy": "Nivel gratuito; Pro a $15/mes; Team a $30/mes para colaboración",
    "MarketMuse": "Precio personalizado según volumen de contenido; típicamente desde varios cientos de dólares al mes",
    "Zapier AI": "IA incluida en planes Zapier; Gratuito con tareas limitadas; Starter a $29.99/mes",
    "ActiveCampaign": "Desde $15/mes para email marketing; Plus a $49/mes; Professional a $79/mes",
    "Mailchimp AI": "Nivel gratuito hasta 500 contactos; Essentials a $13/mes; Standard a $20/mes",
    "Lately AI": "Nivel gratuito; Pro a $39/mes; Business a $79/mes para equipos",
    "QuillBot": "Nivel gratuito; Premium a $8.33/mes (facturado anual) para palabras ilimitadas",
    "Wordtune": "Nivel gratuito; Premium a $9.99/mes; Unlimited a $14.99/mes con IA avanzada",
    "Hemingway App": "Versión web gratuita; App de escritorio a $19.99 (compra única)",
    "Scalenut": "Essential a $39/mes; Growth a $79/mes; Pro a $149/mes",
    "Shortly AI": "Plan mensual a $11/mes; Plan anual a $65/año",
    "Taskade": "Nivel gratuito; Pro a $8/mes con funciones IA; Business a $16/mes",
    "Clockwise": "Nivel gratuito; Pro a $12.50/mes; Enterprise con precio personalizado",
    "Todoist AI": "Nivel gratuito; Pro a $5/mes para funciones IA",
    "Brevo AI": "Nivel gratuito con 300 emails/día; Starter a $9/mes; Business a $25/mes",
    "Buffer AI": "Nivel gratuito con 3 canales; Essentials a $6/mes por canal; Team a $12/mes por canal",
}

with open('C:/Users/Daniel/ai-reviews/data/reviews-en.json', 'r', encoding='utf-8-sig') as f:
    en_data = json.load(f)

for tool in en_data:
    name = tool['name']
    tool['features'] = features_en.get(name, tool['pros'])
    tool['best_for'] = best_for_en.get(name, '')
    tool['pricing_note'] = pricing_note_en.get(name, '')

with open('C:/Users/Daniel/ai-reviews/data/reviews-en.json', 'w', encoding='utf-8') as f:
    json.dump(en_data, f, indent=2, ensure_ascii=False)
print(f'EN: Updated {len(en_data)} tools with features, best_for, pricing_note')

with open('C:/Users/Daniel/ai-reviews/data/reviews-es.json', 'r', encoding='utf-8-sig') as f:
    es_data = json.load(f)

for tool in es_data:
    name = tool['name']
    tool['features'] = features_es.get(name, tool['pros'])
    tool['best_for'] = best_for_es.get(name, '')
    tool['pricing_note'] = pricing_note_es.get(name, '')

with open('C:/Users/Daniel/ai-reviews/data/reviews-es.json', 'w', encoding='utf-8') as f:
    json.dump(es_data, f, indent=2, ensure_ascii=False)
print(f'ES: Updated {len(es_data)} tools with features, best_for, pricing_note')
